import './App.css'

function MainPage() {
  return (
    <>
      <div>
        <div class = "container">
            <div className = "item item-1">January</div>
            <div className = "item item-2">February</div>
            <div className = "item item-3">March</div>
            <div className = "item item-4">April</div>
            <div className = "item item-5">May</div>
            <div className = "item item-6">June</div>
            <div className = "item item-7">July</div>
            <div className = "item item-8">August</div>
            <div className = "item item-9">September</div>
            <div className = "item item-10">October</div>
            <div className = "item item-11">November</div>
            <div className = "item item-12">December</div>
        </div>

        {/* for sticky and fixed */}
        <div class = "container">
            <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Diam sollicitudin tempor id eu nisl. Amet mattis vulputate enim nulla aliquet porttitor lacus luctus accumsan. Risus ultricies tristique nulla aliquet enim. Quam vulputate dignissim suspendisse in. Blandit libero volutpat sed cras ornare. Euismod lacinia at quis risus sed vulputate odio ut enim. Elit sed vulputate mi sit amet mauris commodo quis imperdiet. Elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus. A lacus vestibulum sed arcu non odio euismod. Vulputate eu scelerisque felis imperdiet proin fermentum leo vel. Id venenatis a condimentum vitae sapien pellentesque habitant. Magna eget est lorem ipsum. Egestas sed tempus urna et pharetra pharetra massa massa. In egestas erat imperdiet sed. In fermentum posuere urna nec tincidunt praesent.

Vulputate dignissim suspendisse in est ante in. Magna sit amet purus gravida quis. Mattis enim ut tellus elementum. Ultrices gravida dictum fusce ut. Convallis tellus id interdum velit laoreet id donec ultrices. Odio tempor orci dapibus ultrices. Risus commodo viverra maecenas accumsan lacus vel facilisis. Amet dictum sit amet justo donec enim diam vulputate. Elementum nibh tellus molestie nunc non. Dui accumsan sit amet nulla facilisi morbi tempus iaculis. Quis blandit turpis cursus in hac habitasse platea dictumst. Scelerisque eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada. Scelerisque felis imperdiet proin fermentum leo vel orci porta non. Nascetur ridiculus mus mauris vitae ultricies. Aliquet nibh praesent tristique magna sit amet purus gravida quis. Augue neque gravida in fermentum et sollicitudin ac orci phasellus. Ut tortor pretium viverra suspendisse potenti.

Neque convallis a cras semper auctor. Mi ipsum faucibus vitae aliquet nec ullamcorper sit amet. Aliquam purus sit amet luctus venenatis lectus magna fringilla. Odio facilisis mauris sit amet massa vitae. Elit ullamcorper dignissim cras tincidunt lobortis. Sit amet est placerat in. Molestie nunc non blandit massa enim nec dui nunc. Pretium viverra suspendisse potenti nullam ac tortor vitae purus. Vel fringilla est ullamcorper eget nulla facilisi. Faucibus et molestie ac feugiat sed lectus vestibulum mattis ullamcorper. Metus vulputate eu scelerisque felis imperdiet proin fermentum leo vel. Arcu cursus euismod quis viverra nibh cras pulvinar mattis nunc. Mi quis hendrerit dolor magna eget est lorem. Aenean sed adipiscing diam donec adipiscing tristique risus. Proin nibh nisl condimentum id venenatis a condimentum. Purus gravida quis blandit turpis cursus. Turpis cursus in hac habitasse platea dictumst quisque sagittis. Rhoncus urna neque viverra justo nec ultrices dui sapien. Morbi tristique senectus et netus et malesuada fames. Diam maecenas sed enim ut.

Sed felis eget velit aliquet sagittis id consectetur. Elit eget gravida cum sociis. Adipiscing commodo elit at imperdiet dui accumsan. Rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat. Morbi blandit cursus risus at ultrices mi tempus imperdiet nulla. Nibh mauris cursus mattis molestie. Tincidunt id aliquet risus feugiat in ante metus dictum at. Sollicitudin aliquam ultrices sagittis orci a scelerisque purus semper eget. Velit laoreet id donec ultrices tincidunt arcu non. Purus faucibus ornare suspendisse sed nisi lacus sed viverra. Massa sed elementum tempus egestas sed sed risus pretium.

Lobortis scelerisque fermentum dui faucibus in ornare. Leo integer malesuada nunc vel risus commodo. Mauris vitae ultricies leo integer malesuada. Tristique nulla aliquet enim tortor at auctor urna nunc. Orci phasellus egestas tellus rutrum. Ac ut consequat semper viverra. Lorem ipsum dolor sit amet. Mattis aliquam faucibus purus in massa tempor nec feugiat. Augue interdum velit euismod in pellentesque massa placerat. Sollicitudin ac orci phasellus egestas tellus rutrum tellus pellentesque. Ac felis donec et odio pellentesque. Tempor orci dapibus ultrices in iaculis nunc sed augue lacus. Fermentum odio eu feugiat pretium nibh ipsum consequat nisl. Arcu cursus euismod quis viverra nibh cras. Morbi enim nunc faucibus a pellentesque sit. Nisi est sit amet facilisis magna etiam tempor orci.

Morbi enim nunc faucibus a pellentesque sit. Non odio euismod lacinia at quis risus sed vulputate odio. Congue eu consequat ac felis donec et. Velit dignissim sodales ut eu sem integer vitae justo. Nibh sit amet commodo nulla facilisi nullam vehicula ipsum. Id cursus metus aliquam eleifend mi in nulla posuere sollicitudin. Hac habitasse platea dictumst quisque. In fermentum et sollicitudin ac orci phasellus egestas tellus. Odio euismod lacinia at quis risus sed vulputate odio ut. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa eget. Facilisis gravida neque convallis a cras. Nunc id cursus metus aliquam eleifend.

Est placerat in egestas erat imperdiet sed euismod nisi. Adipiscing elit pellentesque habitant morbi tristique senectus et netus. At consectetur lorem donec massa sapien. Feugiat sed lectus vestibulum mattis ullamcorper velit sed ullamcorper. Curabitur vitae nunc sed velit dignissim sodales. Lacus sed viverra tellus in. Ullamcorper velit sed ullamcorper morbi tincidunt ornare. Eu non diam phasellus vestibulum lorem. Orci eu lobortis elementum nibh tellus molestie nunc non blandit. Aliquam ut porttitor leo a. Feugiat vivamus at augue eget arcu. Donec ultrices tincidunt arcu non. Non diam phasellus vestibulum lorem sed risus ultricies tristique. Nunc mattis enim ut tellus. Id ornare arcu odio ut sem nulla pharetra. At lectus urna duis convallis. Pellentesque diam volutpat commodo sed egestas.

Vitae sapien pellentesque habitant morbi tristique senectus et netus. Enim praesent elementum facilisis leo vel fringilla est ullamcorper. Morbi leo urna molestie at elementum eu facilisis sed odio. Nisl rhoncus mattis rhoncus urna neque. At imperdiet dui accumsan sit. Non tellus orci ac auctor augue mauris augue. Sit amet facilisis magna etiam tempor. Pulvinar sapien et ligula ullamcorper malesuada. Rhoncus mattis rhoncus urna neque viverra. Adipiscing elit ut aliquam purus. Morbi tristique senectus et netus et malesuada fames ac.

Montes nascetur ridiculus mus mauris vitae ultricies leo integer malesuada. Enim facilisis gravida neque convallis a cras semper. Id volutpat lacus laoreet non curabitur gravida arcu ac. Eget egestas purus viverra accumsan in. Proin sagittis nisl rhoncus mattis rhoncus. Lobortis feugiat vivamus at augue. Laoreet sit amet cursus sit amet dictum sit amet justo. Enim facilisis gravida neque convallis a cras semper. Pharetra magna ac placerat vestibulum. Volutpat ac tincidunt vitae semper quis lectus nulla at. Etiam sit amet nisl purus in mollis nunc. Duis ut diam quam nulla porttitor massa id neque aliquam. Semper feugiat nibh sed pulvinar proin gravida hendrerit lectus. Feugiat scelerisque varius morbi enim nunc faucibus a pellentesque. Vitae ultricies leo integer malesuada nunc vel risus commodo viverra. Aenean vel elit scelerisque mauris pellentesque pulvinar. Augue neque gravida in fermentum et sollicitudin ac orci phasellus. Tellus in metus vulputate eu scelerisque. Condimentum lacinia quis vel eros. Cursus mattis molestie a iaculis at erat pellentesque adipiscing.

A lacus vestibulum sed arcu non odio euismod lacinia at. Pharetra massa massa ultricies mi quis hendrerit dolor magna. Neque convallis a cras semper auctor. Rhoncus dolor purus non enim praesent elementum facilisis leo vel. Arcu bibendum at varius vel pharetra vel turpis. Ullamcorper velit sed ullamcorper morbi. Elit ut aliquam purus sit amet luctus. Quam viverra orci sagittis eu volutpat odio facilisis. Mauris vitae ultricies leo integer. Arcu bibendum at varius vel pharetra vel turpis. Lobortis feugiat vivamus at augue eget arcu dictum varius. Id nibh tortor id aliquet lectus proin. Arcu ac tortor dignissim convallis aenean et. Suspendisse potenti nullam ac tortor vitae purus faucibus ornare suspendisse. Elementum integer enim neque volutpat ac tincidunt vitae. Feugiat sed lectus vestibulum mattis.

Sapien faucibus et molestie ac. Odio eu feugiat pretium nibh ipsum. Semper auctor neque vitae tempus quam pellentesque nec. Ac turpis egestas maecenas pharetra convallis. Dignissim cras tincidunt lobortis feugiat vivamus at augue. At ultrices mi tempus imperdiet. Et tortor at risus viverra adipiscing at in tellus. Tincidunt eget nullam non nisi est sit amet. Lectus quam id leo in vitae. Egestas maecenas pharetra convallis posuere. Libero justo laoreet sit amet cursus sit amet dictum sit. Nunc mi ipsum faucibus vitae aliquet nec ullamcorper. Donec massa sapien faucibus et molestie ac feugiat. Scelerisque viverra mauris in aliquam sem. Tellus pellentesque eu tincidunt tortor aliquam. Sed id semper risus in hendrerit gravida rutrum quisque. Gravida neque convallis a cras. Eget egestas purus viverra accumsan in. Ac odio tempor orci dapibus ultrices in iaculis nunc. Scelerisque fermentum dui faucibus in ornare quam viverra orci sagittis.

Et odio pellentesque diam volutpat commodo sed egestas egestas fringilla. Nulla facilisi etiam dignissim diam quis. Non nisi est sit amet facilisis magna etiam tempor. Sed felis eget velit aliquet sagittis id. Consequat ac felis donec et. Maecenas pharetra convallis posuere morbi leo urna molestie at. Egestas pretium aenean pharetra magna ac placerat vestibulum lectus mauris. Aliquet porttitor lacus luctus accumsan tortor posuere ac. Consectetur adipiscing elit duis tristique sollicitudin nibh sit amet. Cras sed felis eget velit aliquet sagittis id consectetur purus. Faucibus ornare suspendisse sed nisi lacus. Pulvinar etiam non quam lacus. Magna fermentum iaculis eu non diam. Tellus at urna condimentum mattis. Nunc sed id semper risus. Dolor sit amet consectetur adipiscing.

Urna id volutpat lacus laoreet non curabitur gravida arcu ac. Vestibulum sed arcu non odio. Ullamcorper malesuada proin libero nunc consequat interdum varius sit amet. Leo a diam sollicitudin tempor id. Velit scelerisque in dictum non consectetur a. Velit ut tortor pretium viverra suspendisse potenti nullam ac. Vel facilisis volutpat est velit. Lacus viverra vitae congue eu consequat ac felis. Euismod elementum nisi quis eleifend quam adipiscing vitae proin. Ut consequat semper viverra nam libero justo laoreet sit. Maecenas sed enim ut sem viverra. Cursus mattis molestie a iaculis at. Orci nulla pellentesque dignissim enim sit amet venenatis urna cursus. Purus in mollis nunc sed id. ̰
Lacus viverra vitae congue eu. Sed risus ultricies tristique nulla aliquet. Neque egestas congue quisque egestas diam in arcu cursus euismod. Pulvinar mattis nunc sed blandit. Pretium quam vulputate dignissim suspendisse. Faucibus ornare suspendisse sed nisi. Ullamcorper dignissim cras tincidunt lobortis feugiat vivamus at augue eget. Tellus elementum sagittis vitae et leo duis ut diam quam. Ipsum dolor sit amet consectetur adipiscing elit. Vitae et leo duis ut diam quam nulla porttitor. Pretium vulputate sapien nec sagittis aliquam malesuada bibendum arcu. Facilisi etiam dignissim diam quis enim lobortis scelerisque. Integer malesuada nunc vel risus.

Ut porttitor leo a diam sollicitudin. Lectus sit amet est placerat in egestas erat. Posuere sollicitudin aliquam ultrices sagittis orci a scelerisque purus. Sit amet massa vitae tortor condimentum lacinia quis. Turpis in eu mi bibendum neque. Augue lacus viverra vitae congue eu consequat ac felis. Sit amet consectetur adipiscing elit ut. Tincidunt augue interdum velit euismod in pellentesque massa. A lacus vestibulum sed arcu non odio. Purus semper eget duis at tellus at. Commodo viverra maecenas accumsan lacus vel facilisis. Tincidunt lobortis feugiat vivamus at augue eget arcu dictum varius. Porttitor massa id neque aliquam vestibulum morbi blandit. Ultrices vitae auctor eu augue ut lectus arcu bibendum at. Luctus venenatis lectus magna fringilla. Enim lobortis scelerisque fermentum dui faucibus in ornare quam. Curabitur vitae nunc sed velit dignissim sodales ut. Aliquet porttitor lacus luctus accumsan tortor posuere. Faucibus vitae aliquet nec ullamcorper.

Aliquet risus feugiat in ante metus dictum at tempor. Praesent semper feugiat nibh sed pulvinar proin gravida hendrerit. Mauris commodo quis imperdiet massa. In iaculis nunc sed augue. Pretium aenean pharetra magna ac. Amet facilisis magna etiam tempor orci eu lobortis. Felis eget velit aliquet sagittis id consectetur purus ut faucibus. Mi in nulla posuere sollicitudin aliquam ultrices. Urna neque viverra justo nec ultrices dui sapien eget. Ut pharetra sit amet aliquam id. Eu volutpat odio facilisis mauris sit amet massa vitae tortor. Pulvinar sapien et ligula ullamcorper malesuada proin. Nunc eget lorem dolor sed. Ipsum nunc aliquet bibendum enim. Urna neque viverra justo nec ultrices dui. Facilisis leo vel fringilla est ullamcorper. Proin sed libero enim sed faucibus turpis. Ac ut consequat semper viverra. Nulla malesuada pellentesque elit eget gravida cum. Egestas diam in arcu cursus euismod quis.

Volutpat odio facilisis mauris sit amet massa vitae tortor condimentum. Congue nisi vitae suscipit tellus mauris a diam. Nisl vel pretium lectus quam id leo. At auctor urna nunc id cursus metus aliquam. Vestibulum lorem sed risus ultricies tristique nulla. Adipiscing commodo elit at imperdiet dui. Risus in hendrerit gravida rutrum quisque non tellus orci ac. Justo laoreet sit amet cursus sit amet dictum. Aliquam faucibus purus in massa. Netus et malesuada fames ac turpis egestas. Massa sapien faucibus et molestie ac feugiat sed lectus vestibulum. Vitae congue mauris rhoncus aenean vel elit scelerisque. Morbi quis commodo odio aenean sed adipiscing diam donec. Amet est placerat in egestas erat. Posuere sollicitudin aliquam ultrices sagittis. Placerat duis ultricies lacus sed turpis tincidunt. Risus pretium quam vulputate dignissim suspendisse in est. Eu feugiat pretium nibh ipsum consequat nisl vel.

In pellentesque massa placerat duis ultricies lacus sed. Elementum pulvinar etiam non quam lacus suspendisse. Dolor sit amet consectetur adipiscing elit ut. Ac tortor dignissim convallis aenean et tortor. Ultricies tristique nulla aliquet enim tortor at auctor urna nunc. Euismod lacinia at quis risus sed. Aliquam ultrices sagittis orci a scelerisque. Est velit egestas dui id. A lacus vestibulum sed arcu non. Suspendisse potenti nullam ac tortor vitae purus faucibus ornare. Nunc aliquet bibendum enim facilisis gravida neque convallis a.

Odio tempor orci dapibus ultrices in iaculis nunc. Condimentum vitae sapien pellentesque habitant morbi tristique. Massa tincidunt dui ut ornare lectus sit amet. Tellus molestie nunc non blandit massa enim nec dui. Odio pellentesque diam volutpat commodo sed egestas egestas fringilla phasellus. Enim facilisis gravida neque convallis a cras. Eu lobortis elementum nibh tellus molestie nunc non blandit. Odio aenean sed adipiscing diam donec adipiscing tristique risus. Facilisis gravida neque convallis a cras semper. Quisque id diam vel quam. Egestas dui id ornare arcu odio. Diam maecenas ultricies mi eget mauris. Magna etiam tempor orci eu lobortis elementum nibh tellus molestie. In iaculis nunc sed augue lacus viverra vitae. Integer feugiat scelerisque varius morbi. Amet aliquam id diam maecenas ultricies.

Vulputate enim nulla aliquet porttitor lacus luctus. Scelerisque fermentum dui faucibus in. Eget felis eget nunc lobortis mattis aliquam faucibus. Lorem mollis aliquam ut porttitor leo. Arcu risus quis varius quam. Libero justo laoreet sit amet cursus sit. Vestibulum morbi blandit cursus risus. Maecenas ultricies mi eget mauris pharetra et. Risus viverra adipiscing at in tellus integer feugiat scelerisque. Viverra maecenas accumsan lacus vel. Velit sed ullamcorper morbi tincidunt ornare massa eget. Non sodales neque sodales ut. Ut ornare lectus sit amet est placerat in egestas erat. Felis bibendum ut tristique et egestas. At imperdiet dui accumsan sit amet nulla facilisi morbi.
            </p>
        </div>
        
      </div>
    </>
  )
}

export default MainPage
